# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11299\Desktop\其他\qt\简易翻译\trans.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 370)
        self.yuanlan = QtWidgets.QComboBox(Form)
        self.yuanlan.setGeometry(QtCore.QRect(390, 80, 131, 51))
        self.yuanlan.setObjectName("yuanlan")
        self.hou_lan = QtWidgets.QComboBox(Form)
        self.hou_lan.setGeometry(QtCore.QRect(390, 270, 131, 51))
        self.hou_lan.setObjectName("hou_lan")
        self.hou = QtWidgets.QTextBrowser(Form)
        self.hou.setGeometry(QtCore.QRect(10, 200, 341, 131))
        self.hou.setObjectName("hou")
        self.trans = QtWidgets.QPushButton(Form)
        self.trans.setGeometry(QtCore.QRect(400, 180, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.trans.setFont(font)
        self.trans.setObjectName("trans")
        self.yuan = QtWidgets.QTextEdit(Form)
        self.yuan.setGeometry(QtCore.QRect(10, 40, 341, 131))
        self.yuan.setObjectName("yuan")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 340, 141, 20))
        self.label.setObjectName("label")
        self.auto_2 = QtWidgets.QRadioButton(Form)
        self.auto_2.setGeometry(QtCore.QRect(360, 150, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.auto_2.setFont(font)
        self.auto_2.setObjectName("auto_2")
        self.lanout = QtWidgets.QLineEdit(Form)
        self.lanout.setGeometry(QtCore.QRect(460, 150, 71, 20))
        self.lanout.setReadOnly(True)
        self.lanout.setObjectName("lanout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "翻译器"))
        self.trans.setText(_translate("Form", "翻译为"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">ANit TRANSLATOR one1</p><p align=\"center\">0.01.1</p><p align=\"center\"><br/></p></body></html>"))
        self.auto_2.setText(_translate("Form", "自动检测语言："))
